"""setting up the tables round 1 FIGHT

Revision ID: b3d1c3797192
Revises: 
Create Date: 2023-05-01 08:47:45.410745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d1c3797192'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('characters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('character_race', sa.String(), nullable=False),
    sa.Column('character_class', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.user_id'], name=op.f('fk_characters_user_users')),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=75), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_groups_user_id_users')),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('character_groups',
    sa.Column('character_group_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], name=op.f('fk_character_groups_character_id_characters')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('fk_character_groups_group_id_groups')),
    sa.PrimaryKeyConstraint('character_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_groups')
    op.drop_table('groups')
    op.drop_table('characters')
    op.drop_table('users')
    # ### end Alembic commands ###
